# Server configuration
server.port=8080

# MySQL Database connection configuration (Dynamic for Local & AWS Cloud)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/monolithic_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Sidhant@123}

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect